=== ldavidiaz/Universidad/TW/P1/EJERCICIO2/ej2.2.a/respuestas.dtd
<!ELEMENT respuestas (alumno)+>
<!ELEMENT alumno (pregunta)+>
<!ATTLIST alumno
    nombre CDATA #REQUIRED
    apellidos CDATA #REQUIRED
    fecha CDATA #REQUIRED>
<!ELEMENT pregunta (respuesta)+>
<!ATTLIST pregunta 
    id CDATA #REQUIRED>   
<!ELEMENT respuesta (r_test | r_numerica | r_ordenar | r_booleana | r_libre)+>
<!ATTLIST respuesta 
    tipo CDATA #REQUIRED>
<!ELEMENT r_test (#PCDATA)>
<!ATTLIST r_test 
    tipo (unica|multiple) #REQUIRED
    respuestaUnicaOk (A|B|C) #IMPLIED
    respuestaMultipleOk CDATA #IMPLIED>
<!ELEMENT r_numerica (#PCDATA)>
<!ATTLIST r_numerica 
    respuestaOk CDATA #REQUIRED>
<!ELEMENT r_ordenar (frase1_o,frase2_o,frase3_o,frase4_o)>
<!ELEMENT r_booleana (#PCDATA)>
<!ATTLIST r_booleana 
    respuestaOk (si|no|verdadero|falso) #REQUIRED>
<!ELEMENT r_libre (#PCDATA)>
<!ATTLIST r_libre
    respuestaOk CDATA #IMPLIED>
<!ELEMENT frase1_o (#PCDATA)>
<!ATTLIST frase1_o 
    respuestaOk (1|2|3|4) #REQUIRED>
<!ELEMENT frase2_o (#PCDATA)>
<!ATTLIST frase2_o 
    respuestaOk (1|2|3|4) #REQUIRED>
<!ELEMENT frase3_o (#PCDATA)>
<!ATTLIST frase3_o 
    respuestaOk (1|2|3|4) #REQUIRED>
<!ELEMENT frase4_o (#PCDATA)>
<!ATTLIST frase4_o 
    respuestaOk (1|2|3|4) #REQUIRED>

=== ldavidiaz/Universidad/TW/P1/EJERCICIO2/ej2.2.a/respuestas.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE respuestas SYSTEM "respuestas.dtd">
<respuestas>

    <alumno nombre="" apellidos="" fecha="">
        <pregunta id="P1">
            <respuesta tipo="TipoTest">
                <r_test tipo="unica" respuestaUnicaOk="B"><!-- A|B|C-->
                   B
                </r_test>
            </respuesta>
        </pregunta> 

        <pregunta id="P2">
            <respuesta tipo="TipoNumerica">
                <r_numerica respuestaOk="7">
                    7
                </r_numerica>
            </respuesta>

            <respuesta tipo="TipoLibre">
                <r_libre respuestaOk="ejemplo de respuesta">
                    ejemplo de respuesta
                </r_libre>
            </respuesta>
        </pregunta> 

        <pregunta id="P3">
            <respuesta tipo="TipoOrdenar">
                <r_ordenar>
                    <frase1_o respuestaOk="2">2</frase1_o>
                    <frase2_o respuestaOk="3">3</frase2_o>
                    <frase3_o respuestaOk="1">1</frase3_o>
                    <frase4_o respuestaOk="4">4</frase4_o>
                </r_ordenar>
            </respuesta>
        </pregunta> 

        <pregunta id="P4">
            <respuesta tipo="TipoBooleana">
                <r_booleana respuestaOk="si"> si</r_booleana>
            </respuesta>
            <respuesta tipo="TipoLibre">
                <r_libre respuestaOk="">
                    texto libre
                </r_libre>
            </respuesta>
        </pregunta>

        <pregunta id="P5">
            <respuesta tipo="TipoLibre">
                <r_libre>
                    texto libre
                </r_libre>
            </respuesta>
        </pregunta>

        <pregunta id="6">
            <respuesta tipo="TipoNumerica">
                <r_numerica respuestaOk="7">
                    7
                </r_numerica>
            </respuesta>
        </pregunta>
    </alumno>

    <alumno nombre="" apellidos="" fecha="">
        <pregunta id="P1">
            <respuesta tipo="TipoTest">
                <r_test tipo="unica" respuestaUnicaOk="B"><!-- A|B|C-->
                   B
                </r_test>
            </respuesta>
        </pregunta> 

        <pregunta id="P2">
            <respuesta tipo="TipoNumerica">
                <r_numerica respuestaOk="7">
                    7
                </r_numerica>
            </respuesta>

            <respuesta tipo="TipoLibre">
                <r_libre respuestaOk="ejemplo de respuesta">
                    ejemplo de respuesta
                </r_libre>
            </respuesta>
        </pregunta> 

        <pregunta id="P3">
            <respuesta tipo="TipoOrdenar">
                <r_ordenar>
                    <frase1_o respuestaOk="2">2</frase1_o>
                    <frase2_o respuestaOk="3">3</frase2_o>
                    <frase3_o respuestaOk="1">1</frase3_o>
                    <frase4_o respuestaOk="4">4</frase4_o>
                </r_ordenar>
            </respuesta>
        </pregunta> 

        <pregunta id="P4">
            <respuesta tipo="TipoBooleana">
                <r_booleana respuestaOk="si"> si</r_booleana>
            </respuesta>
            <respuesta tipo="TipoLibre">
                <r_libre respuestaOk="">
                    texto libre
                </r_libre>
            </respuesta>
        </pregunta>

        <pregunta id="P5">
            <respuesta tipo="TipoLibre">
                <r_libre>
                    texto libre
                </r_libre>
            </respuesta>
        </pregunta>

        <pregunta id="6">
            <respuesta tipo="TipoNumerica">
                <r_numerica respuestaOk="7">
                    7
                </r_numerica>
            </respuesta>
        </pregunta>
    </alumno>
</respuestas>
