=== ldavidiaz/Universidad/TW/P1/EJERCICIO2/ej2.1.a/examen.dtd
<!-- LUIS DAVID DIAZ MESA
SERGIO MONTALBÁN ATENCIA-->
<!ELEMENT examen (pregunta)+>
<!ELEMENT pregunta (id?,enunciado,(p_test | p_numerica | p_orden | p_bool | p_libre)+)+ >
<!ATTLIST pregunta 
    nombre CDATA #REQUIRED
    primerApellido CDATA #REQUIRED
    segundoApellido CDATA #IMPLIED
    fechaCreacion CDATA #IMPLIED
    >
<!ELEMENT id (#PCDATA) >
<!ATTLIST id
        id CDATA #REQUIRED>
<!ELEMENT enunciado (#PCDATA) >
<!ELEMENT p_test (test1,test2,test3)+ >
<!ATTLIST p_test 
        tipo (unica|multiple) #IMPLIED>
<!ELEMENT p_numerica EMPTY >
<!ATTLIST p_numerica
        min CDATA #REQUIRED
        max CDATA #REQUIRED>
<!ELEMENT p_orden (orden1,orden2,orden3,orden4) ><!-- partes de un documento XML: 1.declarion xml 2.doctype 3.Elemento raiz 4.subelemento-->
<!ELEMENT p_bool (#PCDATA)><!-- pregunta si o no-->
<!ATTLIST p_bool
    respuesta (si|no|verdadero|falso) #REQUIRED>
<!ELEMENT p_libre EMPTY >
<!ATTLIST p_libre
        numfilas CDATA #REQUIRED
        numcol CDATA #REQUIRED>
<!ELEMENT num (#PCDATA)>
<!ELEMENT letra (#PCDATA)>
<!ELEMENT test1 (#PCDATA)>
<!ELEMENT test2 (#PCDATA)>
<!ELEMENT test3 (#PCDATA)>
<!ELEMENT orden1 (#PCDATA)>
<!ELEMENT orden2 (#PCDATA)>
<!ELEMENT orden3 (#PCDATA)>
<!ELEMENT orden4 (#PCDATA)>

=== ldavidiaz/Universidad/TW/P1/EJERCICIO2/ej2.1.a/examen.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- LUIS DAVID DIAZ MESA
SERGIO MONTALBÁN ATENCIA-->
<!DOCTYPE examen SYSTEM "examen.dtd">
<examen>
    <!-- TIPO TEST -->
    <pregunta nombre="Luis David" primerApellido="Diaz">
        <id id="P1"></id>
        <enunciado>
        </enunciado>
        <p_test tipo="unica">
            <test1><!-- ESTO ES UN EJEMPLO--></test1>
            <test2><!-- ESTO ES UN EJEMPLO--></test2>
            <test3><!-- ESTO ES UN EJEMPLO--></test3>
        </p_test>
    </pregunta>

    <!-- TIPO NUMERICA-->
    <pregunta nombre="Luis David" primerApellido="Diaz">
        <id id="P2"></id>
        <enunciado>
            ¿Cuántos valores por defecto tienen los atributos?
        </enunciado>
        <p_numerica min="1 " max="5"></p_numerica>
       <!--
        <id id="P2a"></id>
       -->
        <enunciado><!-- ¿Cuáles son?-->
            ¿Cuáles son?
        </enunciado>
        <p_libre numfilas="2" numcol="1"></p_libre>
    </pregunta>

    <!-- TIPO ORDENAMIENTO-->
    <pregunta nombre="Luis David" primerApellido="Diaz">
        <id id="P3"></id>
        <enunciado>
            <!-- ESTO ES UN EJEMPLO-->
        </enunciado>
        <p_orden>
            <orden1><!-- ESTO ES UN EJEMPLO--></orden1>
            <orden2><!-- ESTO ES UN EJEMPLO--></orden2>
            <orden3><!-- ESTO ES UN EJEMPLO--></orden3>
            <orden4><!-- ESTO ES UN EJEMPLO--></orden4>
        </p_orden>
    </pregunta>

    <!-- TIPO BOOLEANA-->
    <pregunta nombre="Luis David" primerApellido="Diaz">
        <id id="P4"></id>
        <enunciado>
            ¿Se puede declarar un atributo si este modifica el valor del elemento?
        </enunciado>
        <p_bool respuesta="si">
        </p_bool>
        <!--
        <id id="P4a"></id>
        -->
        <enunciado>
            Justifica tu respuesta 
        </enunciado>
        <p_libre numfilas="3" numcol="1"></p_libre>
    </pregunta>

    <!-- TIPO LIBRE-->
    <pregunta nombre="Luis David" primerApellido="Diaz">
        <id id="P5"></id>
        <enunciado>
        </enunciado>
        <p_libre numfilas="4" numcol="1"></p_libre>
    </pregunta>

    <!-- TIPO NUMERICA -->
    <pregunta nombre="Luis David" primerApellido="Diaz">   
        <id id="P6" />
        <enunciado>
            ¿Qué nota le pondrías a esta práctica?
        </enunciado>
        <p_numerica min="5" max="10" />
    </pregunta>
</examen>
