=== ldavidiaz/Universidad/TW/P1/EJERCICIO2/ej2.1.b/examen.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- LUIS DAVID DIAZ MESA
SERGIO MONTALBÁN ATENCIA-->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="examen" type="tipoExamen"/>

    <xsd:complexType name="tipoExamen">
        <xsd:sequence>
            <xsd:element name="pregunta" minOccurs="6" maxOccurs="unbounded" type="tipoPregunta"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="tipoPregunta">
        <xsd:choice minOccurs="1" maxOccurs="unbounded">
            <xsd:element name="id" minOccurs="1" maxOccurs="unbounded" type="TipoId"></xsd:element>
            <xsd:element name="enunciado" minOccurs="1" maxOccurs="unbounded" type="xsd:string"></xsd:element>
            <xsd:element name="p_test" type="tipoTest"></xsd:element>
            <xsd:element name="p_numerica" type="TipoNumerica"></xsd:element>
            <xsd:element name="p_ordenar" type="tipoOrdenar"></xsd:element>
            <xsd:element name="p_booleana" type="tipoBooleana"></xsd:element>
            <xsd:element name="p_libre" type="tipoLibre"></xsd:element>
        </xsd:choice>
        <xsd:attribute name="nombre" type="xsd:string" use="required"></xsd:attribute>
        <xsd:attribute name="primerApellido" type="xsd:string" use="required"></xsd:attribute>
        <xsd:attribute name="segundoApellido" type="xsd:string" use="optional"></xsd:attribute>
        <xsd:attribute name="fechaCreacion" type="xsd:date" use="optional"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="TipoId">
        <xsd:attribute name="id"  type="xsd:string" use="required"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="tipoTest">
        <xsd:all>
            <xsd:element name="A" type="xsd:string"></xsd:element>
            <xsd:element name="B" type="xsd:string"></xsd:element>
            <xsd:element name="C" type="xsd:string"></xsd:element>
        </xsd:all>
        <xsd:attribute name="tipo" type="TipoEleccion"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="TipoNumerica">
        <xsd:attribute name="min" type="xsd:string" use="required"></xsd:attribute>
        <xsd:attribute name="max" type="xsd:string" use="required"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="tipoOrdenar">
        <xsd:all>
            <xsd:element name="opcion1" type="xsd:string"></xsd:element>
            <xsd:element name="opcion2" type="xsd:string"></xsd:element>
            <xsd:element name="opcion3" type="xsd:string"></xsd:element>
            <xsd:element name="opcion4" type="xsd:string"></xsd:element>
        </xsd:all>
    </xsd:complexType>

    <xsd:complexType name="tipoBooleana">
        <xsd:attribute name="respuesta" type="tipoRespuesta" use="required"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="tipoLibre">
        <xsd:attribute name="numfilas" use="required"></xsd:attribute>
        <xsd:attribute name="numcol" use="required"></xsd:attribute>
    </xsd:complexType>

    <xsd:simpleType name="TipoEleccion">
        <xsd:restriction  base="xsd:string">
         <xsd:enumeration value="unica"/>
         <xsd:enumeration value="multiple"/>
        </xsd:restriction>
     </xsd:simpleType>


    <xsd:simpleType name="tipoRespuesta">
        <xsd:restriction  base="xsd:string">
         <xsd:enumeration value="si"/>
         <xsd:enumeration value="no"/>
         <xsd:enumeration value="verdadero"/>
         <xsd:enumeration value="falso"/>
        </xsd:restriction>
     </xsd:simpleType>
</xsd:schema>

=== ldavidiaz/Universidad/TW/P1/EJERCICIO2/ej2.1.b/examen2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- LUIS DAVID DIAZ MESA
SERGIO MONTALBÁN ATENCIA-->
<examen
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="examen.xsd">

    <!-- TIPO TEST -->
    <pregunta nombre="Luis David" primerApellido="Diaz">
        <id id="P1"></id>
        <enunciado>
             <!-- ESTO ES UN EJEMPLO-->
        </enunciado>
        <p_test tipo="unica">
            <A> <!-- ESTO ES UN EJEMPLO--></A>
            <B> <!-- ESTO ES UN EJEMPLO--></B>
            <C> <!-- ESTO ES UN EJEMPLO--></C>
        </p_test>
    </pregunta>

    <!-- TIPO NUMERICA-->
    <pregunta nombre="Luis David" primerApellido="Diaz">
        <id id="P2"></id>
        <enunciado>
            ¿Cuántos atributos puede tener la declaración :element en xsd? 
        </enunciado>
        <p_numerica min="0" max="7"></p_numerica>
        <enunciado>
            ¿Cuáles son? Explica para que sirven.
        </enunciado>
        <p_libre numfilas="16" numcol="1"></p_libre>
    </pregunta>

    <!-- TIPO ORDENAMIENTO-->
    <pregunta nombre="Luis David" primerApellido="Diaz">
        <id id="P3"></id>
        <enunciado>
            <!-- ESTO ES UN EJEMPLO-->
        </enunciado>
        <p_ordenar>
            <opcion2> <!-- ESTO ES UN EJEMPLO--></opcion2>
            <opcion1> <!-- ESTO ES UN EJEMPLO--></opcion1>
            <opcion4> <!-- ESTO ES UN EJEMPLO--></opcion4>
            <opcion3> <!-- ESTO ES UN EJEMPLO--></opcion3>
        </p_ordenar>
    </pregunta>

    <!-- TIPO BOOLEANA-->
    <pregunta nombre="Luis David" primerApellido="Diaz">
        <id id="P4"></id>
        <enunciado>
            ¿Se puede declarar un atributo si este modifica el valor del elemento?
        </enunciado>
        <p_booleana respuesta="si"></p_booleana>
        <enunciado>
            Justifica tu respuesta 
        </enunciado>
        <p_libre numfilas="3" numcol="1"></p_libre>
    </pregunta>

    <!-- TIPO LIBRE-->
    <pregunta nombre="Luis David" primerApellido="Diaz">
        <id id="P5"></id>
        <enunciado>
            ¿Qué atributos puede tener la declaración :attribute en xsd? Explica para que sirven.
        </enunciado>
        <p_libre numfilas="12" numcol="1"></p_libre>
    </pregunta>
    
    <!-- TIPO NUMERICA -->
    <pregunta nombre="Luis David" primerApellido="Diaz">   
        <id id="P6" />
        <enunciado>¿Qué nota le pondrías a esta práctica?</enunciado>
        <p_numerica min="5" max="10" />
    </pregunta>
</examen>
